version: "1"
services:
  lanstreamer-api:
    image: lanstreamer-api:latest
    container_name: lanstreamer-api
    ports:
      - 5000:80
  lanstreamer-web:
    image: lanstreamer-web
    container_name: lanstreamer-web
    ports:
      - 443:80
